import { chromium } from 'playwright';
import JSZip from 'jszip';
import * as os from 'node:os';
import * as path from 'node:path';
import * as fs from 'node:fs';
import assert from 'node:assert/strict';
const output = fs.mkdtempSync(path.join(os.tmpdir(), 'mdz-ui-'));
if (!process.env.MDZ_BRIDGE_URL) throw new Error('MDZ_BRIDGE_URLにテスト用URLファイルを指定してください');
const url=fs.readFileSync(process.env.MDZ_BRIDGE_URL,'utf8');
const rpc=async(name,...args)=>{const r=await fetch(url+'/rpc/'+name,{method:'POST',body:JSON.stringify(args)});if(!r.ok)throw new Error(await r.text());return r.json()};
(async()=>{
const browser=await chromium.launch({headless:true,executablePath:process.env.MDZ_CHROMIUM || undefined,args:['--no-sandbox','--disable-gpu','--no-zygote']});
const page=await browser.newPage({viewport:{width:1280,height:860}});
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{
if(window.top!==window) return;
const listeners={};window.go={main:{App:new Proxy({},{get:(_,name)=>async(...args)=>{const r=await fetch('/rpc/'+name,{method:'POST',body:JSON.stringify(args)});if(!r.ok)throw new Error(await r.text());return r.json()}})}};
window.runtime={OnFileDrop:fn=>{(listeners['wails:file-drop']??=[]).push(fn)},ResolveFilePaths:(x,y,files)=>{(window as any).__resolvedFileDrop={x,y,names:[...files].map(file=>file.name)}},EventsOn:(name,fn)=>{(listeners[name]??=[]).push(fn)},BrowserOpenURL:()=>{},WindowToggleMaximise:()=>{(window as any).__maximiseCount=((window as any).__maximiseCount||0)+1}};
let pending=false;setInterval(async()=>{if(pending)return;pending=true;try{for(const event of await (await fetch('/events')).json())for(const fn of listeners[event.name]||[])fn(event.data)}finally{pending=false}},50);
});
await page.goto(url);
await page.waitForFunction(()=>!document.querySelector('#welcome').hidden && !document.querySelector('#new').disabled);
await page.locator('#titlebar .titlebar-title').evaluate(node=>node.dispatchEvent(new MouseEvent('dblclick',{bubbles:true,cancelable:true})));
assert.equal(await page.evaluate(()=>(window as any).__maximiseCount),1);
await page.locator('#window-maximise').evaluate(node=>node.dispatchEvent(new MouseEvent('dblclick',{bubbles:true,cancelable:true})));
assert.equal(await page.evaluate(()=>(window as any).__maximiseCount),1);
assert.equal((await rpc('State')).id,'');
await page.locator('#settings').click();
assert.equal(await page.locator('#settings-dialog').getAttribute('open'),'');
assert.equal(await page.locator('#dialog-backdrop').isVisible(),true);
await page.locator('#titlebar .titlebar-title').dblclick();
assert.equal(await page.evaluate(()=>(window as any).__maximiseCount),2);
await page.locator('#window-maximise').click();
assert.equal(await page.evaluate(()=>(window as any).__maximiseCount),3);
assert.deepEqual(await page.locator('[name=initMode] option').allTextContents(),['init.luaを指定','設定なし（--clean）']);
assert.equal(await page.locator('[name=initMode]').inputValue(),'custom');
await page.locator('[name=initMode]').selectOption('clean');
await page.locator('[name=theme]').selectOption('dark'); await page.locator('[name=accent]').selectOption('blue'); await page.locator('#settings-save').click();
await page.waitForFunction(()=>!document.querySelector('#settings-dialog').open && !document.querySelector('#new').disabled);
await page.screenshot({path:path.join(output,'welcome.png')});
await page.locator('#welcome-new').click();
assert.equal(await page.locator('#dialog-backdrop').isVisible(),true);
await page.keyboard.press('Escape');
await page.waitForFunction(()=>!document.querySelector('#new-dialog').open);
assert.equal(await page.locator('#dialog-backdrop').isVisible(),false);
await page.locator('#welcome-new').click(); await page.locator('[data-new-kind=document]').click();
await page.waitForFunction(()=>!document.querySelector('#workspace').hidden && !document.querySelector('#editing').disabled);
assert.equal(await page.locator('#editor').isVisible(),true); assert.equal((await rpc('State')).engine,'builtin');
await page.locator('#sidebar-toggle').click(); assert.equal(await page.locator('.sidebar').isVisible(),false); await page.locator('#sidebar-toggle').click();
assert.equal(await page.locator('#editing').getAttribute('aria-checked'),'true');
assert.equal(await page.locator('#save').evaluate(element=>element.classList.contains('unsaved')),true);
await page.waitForFunction(()=>!document.querySelector('#editor').disabled);
assert.equal(await page.locator('#undo').isDisabled(),true);assert.equal(await page.locator('#redo').isDisabled(),true);
assert.equal(await page.locator('#editor-engine [data-engine=builtin]').getAttribute('aria-pressed'),'true');
assert.equal(await page.locator('#split-mode').getAttribute('aria-pressed'),'true');
const edit=page.locator('#editor');
const ordinaryEntry=(await rpc('State')).entry;
await edit.fill('# 編集テスト\n\n## はじめに\n\n'+'本文です。\n\n'.repeat(80)+'## 後半\n\nここまでスクロールします。');
await page.waitForFunction(()=>[...document.querySelectorAll('#pages .markdown-heading')].some(node=>node.textContent==='後半'));
const currentOrdinaryPage=page.locator('#pages button.current-page');
assert.equal(await currentOrdinaryPage.count(),1);
assert.equal(await currentOrdinaryPage.getAttribute('aria-current'),'page');
assert.equal(await currentOrdinaryPage.getAttribute('data-page'),ordinaryEntry);
assert((await page.locator('#pages').textContent()).includes(ordinaryEntry.split('/').pop()));
assert.deepEqual(await page.locator('#pages .markdown-heading').allTextContents(),['編集テスト','はじめに','後半']);
await page.waitForFunction(()=>document.querySelector('#pages .markdown-heading.active-heading')?.textContent==='編集テスト');
const iframeDropBounds=await page.evaluate(()=>{
	const frame=document.querySelector('#preview') as HTMLIFrameElement;
	const body=frame.contentDocument?.body;
	if(!body) throw new Error('preview iframe is not ready');
	const transfer=new DataTransfer();
	transfer.items.add(new File(['# dropped'],'other.md',{type:'text/markdown'}));
	const bounds=frame.getBoundingClientRect();
	body.dispatchEvent(new DragEvent('drop',{bubbles:true,cancelable:true,dataTransfer:transfer,clientX:17,clientY:23}));
	return {left:bounds.left,top:bounds.top};
});
await page.waitForFunction(()=>(window as any).__resolvedFileDrop?.names?.[0]==='other.md');
const iframeDrop=await page.evaluate(()=>(window as any).__resolvedFileDrop);
assert.deepEqual(iframeDrop.names,['other.md']);
assert.equal(Math.round(iframeDrop.x),Math.round(iframeDropBounds.left+17));
assert.equal(Math.round(iframeDrop.y),Math.round(iframeDropBounds.top+23));
await page.locator('#pages .markdown-heading').filter({hasText:'後半'}).click();
await page.waitForFunction(()=>document.querySelector('#preview').contentWindow?.scrollY>0);
await page.waitForFunction(()=>document.querySelector('#pages .markdown-heading.active-heading')?.textContent==='後半');
await page.evaluate(()=>{
	const frame=document.querySelector('#preview') as HTMLIFrameElement;
	frame.contentWindow?.scrollTo(0,0);
});
await page.waitForFunction(()=>document.querySelector('#pages .markdown-heading.active-heading')?.textContent==='編集テスト');
await page.evaluate(()=>{
	const frame=document.querySelector('#preview') as HTMLIFrameElement;
	const button=[...document.querySelectorAll<HTMLButtonElement>('#pages .markdown-heading')].find(node=>node.textContent==='はじめに');
	const target=button?.dataset.headingId ? frame.contentDocument?.getElementById(button.dataset.headingId) : null;
	target?.scrollIntoView();
});
await page.waitForFunction(()=>document.querySelector('#pages .markdown-heading.active-heading')?.textContent==='はじめに');
await page.evaluate(()=>{const editor=document.querySelector('#editor') as HTMLTextAreaElement;editor.scrollTop=editor.scrollHeight;});
await page.waitForFunction(()=>{const frame=document.querySelector('#preview') as HTMLIFrameElement;const win=frame.contentWindow;const doc=frame.contentDocument;if(!win||!doc)return false;const range=doc.documentElement.scrollHeight-win.innerHeight;return range>0&&win.scrollY/range>.8;});
await page.evaluate(()=>{const frame=document.querySelector('#preview') as HTMLIFrameElement;frame.contentWindow?.scrollTo(0,0);});
await page.waitForFunction(()=>{const editor=document.querySelector('#editor') as HTMLTextAreaElement;return editor.scrollTop<2;});
await page.locator('#files-tab').click();
await page.waitForFunction(entry=>document.querySelector('#pages').textContent.includes(String(entry)),ordinaryEntry.split('/').pop());
await page.locator('#pages-tab').click();
await page.waitForFunction(()=>[...document.querySelectorAll('#pages .markdown-heading')].some(node=>node.textContent==='後半'));
assert.equal(await page.locator('#save').evaluate(element=>element.classList.contains('unsaved')),true);
await page.keyboard.press('Control+s');
await page.waitForFunction(()=>document.querySelector('#status').textContent==='保存しました');
assert.equal(await page.locator('#save').evaluate(element=>element.classList.contains('unsaved')),false);
await page.locator('#settings').click();
await page.locator('[name=undoLevels]').fill('3');await page.locator('[name=imageDirectory]').fill('assets/pasted');
await page.locator('[name=imageName]').fill('capture-{counter}');await page.locator('#settings-save').click();
await page.waitForFunction(()=>!document.querySelector('#settings-dialog').open&&!document.querySelector('#editor').disabled);
assert.equal((await rpc('Settings')).undoLevels,3);
const before=await edit.inputValue();await edit.focus();await page.keyboard.press('Control+End');
const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jGZkAAAAASUVORK5CYII=';
async function pasteImage(target){await page.locator(target).evaluate((node,png)=>{const data=Uint8Array.from(atob(png),x=>x.charCodeAt(0));const dt=new DataTransfer();dt.items.add(new File([data],'clipboard.png',{type:'image/png'}));node.dispatchEvent(new ClipboardEvent('paste',{clipboardData:dt,bubbles:true,cancelable:true}));},png)}
await pasteImage('#editor');await page.waitForFunction(()=>document.querySelector('#editor').value.includes('assets/pasted/capture-001.png'));
await page.waitForFunction(()=>!document.querySelector('#undo').disabled);assert.equal(await page.locator('#redo').isDisabled(),true);
await page.locator('#undo').click();assert.equal(await edit.inputValue(),before);await page.waitForFunction(()=>!document.querySelector('#redo').disabled);
assert.equal((await rpc('State')).assets.length,1);
await page.locator('#redo').click();assert.match(await edit.inputValue(),/capture-001\.png/);
await page.keyboard.press('Control+s');await page.waitForFunction(()=>document.querySelector('#status').textContent==='保存しました');
await page.screenshot({path:path.join(output, 'integrated-builtin.png')});
await page.locator('#settings').click();await page.locator('[name=editor]').selectOption('neovim');await page.locator('#settings-save').click();
await page.waitForFunction(()=>!document.querySelector('#settings-dialog').open&&!document.querySelector('#editor').disabled);
assert.equal((await rpc('Settings')).editor,'neovim');assert.equal((await rpc('State')).engine,'builtin');
await page.locator('#editor-engine [data-engine=neovim]').click();
await page.waitForFunction(()=>document.querySelector('#editor-engine [data-engine=neovim]').getAttribute('aria-pressed')==='true'&&!document.querySelector('#native-input').disabled,{},{timeout:20000});
await page.waitForTimeout(600);await page.locator('#native-input').focus();
await page.keyboard.type('gg0iNATIVE-');await page.keyboard.press('Escape');
await page.waitForFunction(()=>document.querySelector('#editor').value.startsWith('NATIVE-'),{},{timeout:10000});
await page.keyboard.type('u');await page.waitForFunction(()=>!document.querySelector('#editor').value.startsWith('NATIVE-'));
await page.keyboard.press('Control+r');await page.waitForFunction(()=>document.querySelector('#editor').value.startsWith('NATIVE-'));
await pasteImage('#native-input');await page.waitForFunction(()=>document.querySelector('#editor').value.includes('capture-002.png'));
await page.waitForFunction(()=>!document.querySelector('#undo').disabled);await page.locator('#undo').click();await page.waitForFunction(()=>!document.querySelector('#editor').value.includes('capture-002.png'));
await page.locator('#redo').click();await page.waitForFunction(()=>document.querySelector('#editor').value.includes('capture-002.png'));
await page.locator('#native-input').focus();await page.keyboard.press('Escape');await page.keyboard.type(':w');await page.keyboard.press('Enter');
await page.waitForFunction(()=>document.querySelector('#status').textContent==='保存しました');
await page.waitForTimeout(500);await page.screenshot({path:path.join(output, 'integrated-native.png')});
await page.locator('#editor-engine [data-engine=builtin]').click();await page.waitForFunction(()=>document.querySelector('#editor-engine [data-engine=builtin]').getAttribute('aria-pressed')==='true'&&!document.querySelector('#editor').hidden);assert.equal((await rpc('State')).engine,'builtin');
await page.locator('#editor-engine [data-engine=neovim]').click();await page.waitForFunction(()=>document.querySelector('#editor-engine [data-engine=neovim]').getAttribute('aria-pressed')==='true'&&!document.querySelector('#native-input').disabled,{},{timeout:20000});
await page.locator('#settings').click();await page.locator('[name=autoSave]').check();await page.locator('[name=autoSaveSeconds]').fill('5');await page.locator('[name=backupGenerations]').fill('2');await page.locator('#settings-save').click();
await page.waitForFunction(()=>!document.querySelector('#settings-dialog').open&&!document.querySelector('#native-input').disabled);
await page.locator('#native-input').focus();await page.keyboard.type('gg0iAUTOSAVED-');await page.keyboard.press('Escape');
await page.waitForFunction(()=>document.querySelector('#status').textContent==='自動保存しました',{},{timeout:12000});
const info=await (await fetch(url+'/test-info')).json();

const archive=await JSZip.loadAsync(fs.readFileSync(info.saved));
assert.match(await archive.file('本文.md').async('string'),/AUTOSAVED-/);assert(archive.file('assets/pasted/capture-001.png'));assert(archive.file('assets/pasted/capture-002.png'));
const folders=fs.readdirSync(info.base+'/backups');assert.equal(fs.readdirSync(info.base+'/backups/'+folders[0]).filter(x=>x.endsWith('.mdz')).length,2);
await page.locator('#settings').click();await page.screenshot({path:path.join(output, 'settings.png')});await page.locator('#settings-dialog button').filter({hasText:'キャンセル'}).click();
await page.setViewportSize({width:800,height:520});await page.waitForTimeout(500);await page.screenshot({path:path.join(output, 'integrated-compact.png')});
await page.locator('#editing').click();
await page.waitForFunction(()=>document.querySelector('#editing').getAttribute('aria-checked')==='false'&&!document.querySelector('#editing').disabled);
assert.equal(await page.locator('#editor').isVisible(),false); assert.equal((await rpc('State')).engine,'builtin');
assert.equal(await page.locator('#book-sidebar-bottom').isVisible(),false);
await page.locator('#new').click(); await page.locator('[data-new-kind=mdbook]').click();
await page.waitForFunction(()=>document.querySelector('#book-title').textContent==='新規mdBook'&&!document.querySelector('#editing').disabled);
assert((await rpc('State')).pages.includes('src/SUMMARY.md'));
await page.waitForFunction(()=>document.querySelector('#pages').textContent.includes('新規mdBookのテンプレート'));
const currentBookPage=page.locator('#pages button.current-page');
assert.equal(await currentBookPage.count(),1);
assert.equal(await currentBookPage.getAttribute('aria-current'),'page');
assert.equal(await page.locator('#tree-tabs').isVisible(),false);
assert(!((await page.locator('#pages').textContent())||'').includes('SUMMARY.md'));
assert(!((await page.locator('#pages').textContent())||'').includes('book.toml'));
await page.setViewportSize({width:1280,height:860});
await page.screenshot({path:path.join(output,'mdbook-prompt.png')});
if(process.env.MDZ_MDBOOK_TEST) {
 await page.waitForFunction(()=>!document.querySelector('#book-preview').hidden,{},{timeout:30000});
 await page.frameLocator('#book-preview').locator('h1').filter({hasText:'目次'}).or(page.frameLocator('#book-preview').locator('h1').filter({hasText:'新規mdBookのテンプレート'})).first().waitFor();
 await page.screenshot({path:path.join(output,'mdbook-preview.png')});
 await page.keyboard.press('Control+s'); await page.waitForFunction(()=>document.querySelector('#status').textContent==='保存しました');
 const zipped=await JSZip.loadAsync(fs.readFileSync(info.saved)); assert(zipped.file('book.toml')); assert(!Object.keys(zipped.files).some(n=>n.endsWith('.html')));
}
await page.locator('#book-config').click();
await page.waitForFunction(()=>document.querySelector('#book-config-dialog').open&&!document.querySelector('#book-config-edit').disabled);
assert.equal(await page.locator('#book-config-text').getAttribute('readonly'),null);
const bookConfig=await page.locator('#book-config-text').inputValue();
await page.locator('#book-config-text').fill('[broken'); await page.locator('#book-config-save').click();
await page.waitForFunction(()=>document.querySelector('#book-config-error').textContent.includes('TOML'));
await page.locator('#book-config-text').fill(bookConfig.replace('新規mdBook','自分の本')+'\n# 自分のコメントです。\n');
await page.locator('#book-config-save').click();
await page.waitForFunction(()=>!document.querySelector('#book-config-dialog').open&&document.querySelector('#book-title').textContent==='自分の本');
await page.waitForFunction(()=>!document.querySelector('#toc-edit').hidden&&!document.querySelector('#toc-edit').disabled);
assert.equal(await page.locator('#book-title-edit').isVisible(),true);
await page.locator('#book-title-edit').click();
await page.locator('#book-title-input').fill('自分の本（改訂）');
await page.locator('#book-title-form button[type=submit]').click();
await page.waitForFunction(()=>!document.querySelector('#book-title-dialog').open&&document.querySelector('#book-title').textContent==='自分の本（改訂）'&&!document.querySelector('#toc-edit').disabled);
await page.locator('#toc-edit').click();
await page.locator('#toc-add').click();await page.locator('#toc-name').fill('追加した章');await page.locator('#toc-form button[type=submit]').click();
await page.waitForFunction(()=>!document.querySelector('#toc-dialog').open&&document.querySelector('#current').textContent==='追加した章');
await page.locator('[data-toc-op=rename]').click();await page.locator('#toc-name').fill('変更した章');await page.locator('#toc-form button[type=submit]').click();
await page.waitForFunction(()=>!document.querySelector('#toc-dialog').open&&document.querySelector('#pages').textContent.includes('変更した章'));
await page.locator('#toc-undo').click();await page.waitForFunction(()=>document.querySelector('#pages').textContent.includes('追加した章'));
await page.locator('#toc-redo').click();await page.waitForFunction(()=>document.querySelector('#pages').textContent.includes('変更した章'));
await page.screenshot({path:path.join(output,'mdbook-toc-edit.png')});
await page.locator('#book-config').click();await page.locator('#book-config-text').waitFor({state:'visible'});await page.screenshot({path:path.join(output,'mdbook-settings.png')});await page.locator('#book-config-cancel').click();
await page.locator('#editing').click();await page.waitForFunction(()=>document.querySelector('#editing').getAttribute('aria-checked')==='false'&&!document.querySelector('#editing').disabled);
assert.equal(await page.locator('#book-sidebar-bottom').isVisible(),false);
if(process.env.MDZ_MDBOOK_TEST) {
 await page.waitForFunction(()=>!document.querySelector('#book-preview').hidden,{},{timeout:30000});
 assert.equal(await page.locator('#book-panel').isVisible(),false);
 await page.frameLocator('#book-preview').locator('h1').filter({hasText:'追加した章'}).waitFor();
 assert.equal(await page.frameLocator('#book-preview').locator('.sidebar').isVisible(),false);
 assert.equal(await page.frameLocator('#book-preview').locator('#mdbook-sidebar-toggle').isVisible(),false);
 await page.locator('#pages button[data-page="src/guide/editing.md"]').click();
 await page.frameLocator('#book-preview').locator('h1').filter({hasText:'第1章 はじめに'}).waitFor();
 await page.frameLocator('#book-preview').getByRole('link',{name:'図と補足',exact:true}).last().click();
 await page.waitForFunction(()=>document.querySelector('#current').textContent==='図と補足');
 await page.screenshot({path:path.join(output,'mdbook-reader.png')});
}
await page.keyboard.press('Control+s');await page.waitForFunction(()=>document.querySelector('#status').textContent==='保存しました');
const updatedBook=await JSZip.loadAsync(fs.readFileSync(info.saved));
assert.match(await updatedBook.file('book.toml').async('string'),/自分の本/);
assert.match(await updatedBook.file('src/SUMMARY.md').async('string'),/変更した章/);
assert(updatedBook.file('src/chapters/page-001.md'));assert(updatedBook.file('src/images/book.svg'));
assert.deepEqual(errors,[]);
console.log('PASS: real backend + builtin and Neovim UI, clipboard image retention, undo/redo, configurable undo/image paths, :w, autosave, two backup generations; no JavaScript errors');
await browser.close();
await fetch(url+'/test-stop');
console.log('Screenshots:', output);
})().catch(error=>{console.error(error);process.exit(1)});
