import { chromium } from 'playwright';
import JSZip from 'jszip';
import * as fs from 'node:fs';
import * as path from 'node:path';
import * as os from 'node:os';
import assert from 'node:assert/strict';

if (!process.env.MDZ_BRIDGE_URL) throw new Error('MDZ_BRIDGE_URLを指定してください');
const url=fs.readFileSync(process.env.MDZ_BRIDGE_URL,'utf8');
const output=fs.mkdtempSync(path.join(os.tmpdir(),'mdz-slides-ui-'));
const rpc=async(name,...args)=>{const r=await fetch(url+'/rpc/'+name,{method:'POST',body:JSON.stringify(args)});if(!r.ok)throw new Error(await r.text());return r.json()};
const browser=await chromium.launch({headless:true,executablePath:process.env.MDZ_CHROMIUM||undefined,args:['--no-sandbox','--disable-gpu']});
const page=await browser.newPage({viewport:{width:1280,height:860}});
const errors=[];page.on('pageerror',e=>{errors.push(e.message);console.error('PAGE ERROR:',e.stack)});
page.on('console',msg=>{if(msg.type()==='error')console.error('BROWSER:',msg.text());});
await page.addInitScript(()=>{
	if(window.top!==window)return;
	const listeners={};window.go={main:{App:new Proxy({},{get:(_,name)=>async(...args)=>{const r=await fetch('/rpc/'+name,{method:'POST',body:JSON.stringify(args)});if(!r.ok)throw new Error(await r.text());return r.json()}})}};
	window.runtime={OnFileDrop:fn=>{(listeners['wails:file-drop']??=[]).push(fn)},EventsOn:(name,fn)=>{(listeners[name]??=[]).push(fn)},BrowserOpenURL:()=>{}};
	let pending=false;setInterval(async()=>{if(pending)return;pending=true;try{for(const event of await (await fetch('/events')).json())for(const fn of listeners[event.name]||[])fn(event.data)}finally{pending=false}},50);
});
const ready=()=>page.waitForFunction(()=>!document.querySelector('#new').disabled);
const save=async()=>{await ready();await page.locator('#save').click();await page.waitForFunction(()=>document.querySelector('#status').textContent==='保存しました');};
const slide=page.frameLocator('#slide-preview');
const menu=async(label:string)=>{await ready();await page.locator('.slide-card.selected').click({button:'right'});await ready();await page.locator('#slide-context-menu').getByRole('menuitem',{name:label,exact:true}).click();};
const opLabels={duplicate:'複製',up:'上へ移動',undo:'構成を元に戻す',redo:'構成をやり直す',remove:'削除',add:'スライドを追加'};
try {
	await page.goto(url);await ready();
	await page.locator('#welcome-new').click();await page.locator('[data-new-kind=slides]').click();await ready();
	await slide.locator('section h1').filter({hasText:'新規スライド'}).waitFor();
	assert.equal((await rpc('State')).mode,'slides');
	assert.equal(await page.locator('.slide-card').count(),8);
	await page.screenshot({path:path.join(output,'slides-reader.png')});
	await page.evaluate(()=>{const sidebar=document.querySelector('#sidebar');sidebar.scrollTop=sidebar.scrollHeight;window.thumbnailBefore=document.querySelector('.slide-card:last-child iframe');window.sidebarBefore=sidebar.scrollTop;});
	await page.locator('.slide-card').last().click();await ready();
	assert(await page.evaluate(()=>window.thumbnailBefore===document.querySelector('.slide-card:last-child iframe')));
	assert(await page.evaluate(()=>Math.abs(window.sidebarBefore-document.querySelector('#sidebar').scrollTop)<2));
	await page.locator('.slide-card').first().click();await ready();
	assert.equal(await page.locator('#editing').getAttribute('aria-checked'),'true');
	const originalSlideIDs=(await rpc('Slides')).deck.slides.map(s=>s.id);
	await page.locator('.slide-card').nth(1).hover();await page.mouse.down();
	const insertionTarget=await page.locator('.slide-card').first().boundingBox();
	await page.mouse.move(insertionTarget.x+40,insertionTarget.y+3,{steps:8});await page.mouse.move(insertionTarget.x+41,insertionTarget.y+4);
	await page.locator('.slide-insert-before').waitFor();
	assert.equal(await page.locator('.slide-insert-before').evaluate(node=>getComputedStyle(node).overflow),'visible');
	assert.equal(await page.locator('.slide-insert-before').evaluate(node=>getComputedStyle(node,'::before').borderTopStyle),'dashed');
	await page.screenshot({path:path.join(output,'slide-insert.png')});await page.mouse.up();
	await page.waitForFunction(()=>document.querySelector('.slide-card').dataset.slide==='slide-002');await ready();
	assert.equal((await rpc('Slides')).deck.slides[0].id,'slide-002');
	await menu('構成を元に戻す');await ready();assert.deepEqual((await rpc('Slides')).deck.slides.map(s=>s.id),originalSlideIDs);
	let checkpointStarted; const checkpoint = new Promise<void>(resolve => checkpointStarted = resolve);
	let resumeCheckpoint; const checkpointGate = new Promise<void>(resolve => resumeCheckpoint = resolve);
	await page.route('**/rpc/Update', async route => { checkpointStarted(); await checkpointGate; await route.continue(); }, {times:1});
	await page.locator('#editor').fill('# 調査結果\n\n- ページごとにMarkdown\n- オフラインで発表\n\n---\n\n水平線は改ページしません。');
	await slide.locator('h1').filter({hasText:'調査結果'}).waitFor();
	assert.equal(await slide.locator('section').count(),1);assert.equal(await slide.locator('hr').count(),1);
	await checkpoint;
	try {
		assert.equal(await page.locator('#editor').isEnabled(),true);
		assert.equal(await page.locator('#slides-settings').isEnabled(),true);
		await page.locator('#editor').fill((await page.locator('#editor').inputValue())+'\n\n保存中の追記');
		await page.locator('#slides-settings').click();
		await page.locator('#deck-title').waitFor({state:'visible'});
	} finally { resumeCheckpoint(); }
	await page.locator('#deck-title').fill('技術発表');await page.locator('#slide-title').fill('調査結果');await page.locator('#slide-layout').selectOption('standard');await page.locator('#slide-notes').fill('画面には見せないメモ');await page.locator('#deck-margin').fill('#f0f0f0');await page.locator('#slides-settings-save').click();await ready();
	assert.equal(await page.locator('#slide-typography-apply').count(),0);
	await page.locator('#slide-font-family').selectOption('mincho');await page.locator('#slide-margin-x').fill('44');await page.locator('#slide-margin-y').fill('36');await page.locator('#slide-body-size').fill('28');await page.locator('#slide-h1-size').fill('50');await page.locator('#slide-h2-size').fill('44');await page.locator('#slide-h3-size').fill('40');await page.locator('#slide-h4-size').fill('36');await page.locator('#slide-h5-size').fill('32');
	await page.waitForFunction(()=>{const section=document.querySelector('#slide-preview').contentDocument.querySelector('section');const h1=section?.querySelector('h1');return section&&getComputedStyle(section).paddingLeft==='44px'&&getComputedStyle(section).paddingTop==='36px'&&getComputedStyle(section).fontSize==='28px'&&h1&&getComputedStyle(h1).fontSize==='50px';});
	let typography;
	for(let attempt=0;attempt<40;attempt++){typography=(await rpc('Slides')).deck;if(typography.fontFamily==='mincho'&&typography.contentMarginX===44&&typography.contentMarginY===36&&typography.bodyFontSize===28&&typography.h1FontSize===50)break;await page.waitForTimeout(50);}
	assert.equal(typography.fontFamily,'mincho');assert.equal(typography.contentMarginX,44);assert.equal(typography.contentMarginY,36);assert.equal(typography.bodyFontSize,28);assert.equal(typography.h1FontSize,50);
	assert.equal(await slide.locator('section').evaluate(node=>getComputedStyle(node).paddingLeft),'44px');assert.equal(await slide.locator('section').evaluate(node=>getComputedStyle(node).paddingTop),'36px');assert.equal(await slide.locator('section').evaluate(node=>getComputedStyle(node).fontSize),'28px');assert.equal(await slide.locator('h1').evaluate(node=>getComputedStyle(node).fontSize),'50px');
	await menu(opLabels.duplicate);await ready();
	assert.equal(await page.locator('.slide-card').count(),9);assert.equal((await rpc('Slides')).deck.slides[1].notes,'画面には見せないメモ');
	const copy=(await rpc('Slides')).deck.slides[1];
	await menu(opLabels.up);await ready();assert.equal((await rpc('Slides')).deck.slides[0].id,copy.id);
	await menu(opLabels.undo);await ready();assert.equal((await rpc('Slides')).deck.slides[1].id,copy.id);
	await menu(opLabels.redo);await ready();assert.equal((await rpc('Slides')).deck.slides[0].id,copy.id);
	page.once('dialog',d=>d.accept());await menu(opLabels.remove);await ready();assert.equal(await page.locator('.slide-card').count(),8);
	await menu(opLabels.undo);await ready();assert.equal(await page.locator('.slide-card').count(),9);
	await menu(opLabels.add);await ready();
	await page.locator('#editor').fill('# 比較\n\n- 左の内容\n\n<!-- column -->\n\n# 結果\n\n- 右の内容');
	await page.locator('#slides-settings').click();await page.locator('#slide-title').fill('比較');await page.locator('#slide-layout').selectOption('columns');await page.locator('#slides-settings-save').click();await ready();
	await slide.locator('.slide-columns').waitFor();
	await page.screenshot({path:path.join(output,'slides-editor.png')});
	const png='iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jGZkAAAAASUVORK5CYII=';
	await page.locator('#editor').focus();await page.keyboard.press('Control+End');await page.keyboard.press('Enter');
	await page.locator('#editor').evaluate((node,png)=>{const dt=new DataTransfer();dt.items.add(new File([Uint8Array.from(atob(png),c=>c.charCodeAt(0))],'p.png',{type:'image/png'}));node.dispatchEvent(new ClipboardEvent('paste',{clipboardData:dt,bubbles:true,cancelable:true}));},png);
	await page.waitForFunction(()=>document.querySelector('#editor').value.includes('![画像]'));
	await slide.locator('img').waitFor();await page.waitForFunction(()=>{const i=document.querySelector('#slide-preview').contentDocument.querySelector('img');return i?.complete&&i.naturalWidth===1;});
	await ready();await menu('Markdownを取り込む');await page.locator('#slides-import-text').fill('# 取り込み1\n\n---\n\n# 取り込み2\n\n```md\n---\n```');await page.locator('#slides-import-form button[type=submit]').click();await ready();assert.equal(await page.locator('.slide-card').count(),12);
	await page.locator('#editor').fill('# 長いページ\n\n'+Array.from({length:30},(_,i)=>'- 項目'+i).join('\n'));
	await page.locator('#slide-overflow').waitFor({state:'visible'});
	const overflowPreview=await slide.locator('.slides>section.present').evaluate(section=>{const last=section.querySelector('.slide-content li:last-child');const slideRect=section.getBoundingClientRect();const lastRect=last?.getBoundingClientRect();const style=getComputedStyle(section);return{editorPreview:document.documentElement.classList.contains('editor-preview'),overflow:style.overflow,outlineStyle:style.outlineStyle,outlineColor:style.outlineColor,protrudes:!!lastRect&&lastRect.bottom>slideRect.bottom};});
	assert.equal(overflowPreview.editorPreview,true);assert.equal(overflowPreview.overflow,'visible');assert.equal(overflowPreview.outlineStyle,'solid');assert.equal(overflowPreview.outlineColor,'rgb(0, 0, 0)');assert.equal(overflowPreview.protrudes,true);
	assert.equal(await page.locator('#slide-typography #slide-debug-outline').count(),0);
	assert.equal(await page.locator('#slide-debug-outline').getAttribute('aria-checked'),'false');
	await page.locator('#slide-debug-outline').click();await page.waitForFunction(()=>document.querySelector('#slide-preview').contentDocument.documentElement.classList.contains('debug-outline'));
	assert.equal(await page.locator('#slide-debug-outline').getAttribute('aria-checked'),'true');
	assert.equal(await slide.locator('.slide-content').evaluate(node=>getComputedStyle(node).outlineStyle),'solid');
	assert.equal(await slide.locator('li').first().evaluate(node=>getComputedStyle(node).outlineStyle),'dotted');
	await page.locator('#slide-debug-outline').click();await page.waitForFunction(()=>!document.querySelector('#slide-preview').contentDocument.documentElement.classList.contains('debug-outline'));
	assert.equal(await page.locator('#slide-debug-outline').getAttribute('aria-checked'),'false');
	await page.locator('#editor').fill('# 分割A\n\n---\n\n# 分割B\n\n```md\n---\n```');await page.locator('#slide-split').click();await ready();
	assert.equal(await page.locator('.slide-card').count(),13);assert((await page.locator('#editor').inputValue()).includes('# 分割A'));
	await menu(opLabels.undo);await ready();assert.equal(await page.locator('.slide-card').count(),12);assert((await page.locator('#editor').inputValue()).includes('# 分割B'));
	await page.locator('#editor').fill('# 取り込み1\n\n短い本文');await page.locator('#slide-overflow').waitFor({state:'hidden'});
	await page.locator('#editor').fill('# 目次\n\n1. 背景・目的\n2. 作業内容\n3. 開発\n4. QC\n5. 開発条件・動作保証環境\n6. 体制・スケジュール\n\nAppendix\n\n- A. ご依頼内容\n- B. 開発環境作成・デバッグの仕方\n- C. QC検査手順');await page.locator('#slide-overflow').waitFor({state:'hidden'});
	await save();
	await page.locator('.slide-card').first().click();await ready();
	await page.locator('#editing').click();await ready();assert.equal(await page.locator('#editing').getAttribute('aria-checked'),'false');
	await slide.locator('section.present').hover();await page.mouse.wheel(0,100);await page.waitForFunction(()=>document.querySelector('#slide-position').textContent?.startsWith('2 / '));
	await slide.locator('section.present').hover();await page.mouse.wheel(0,-100);await page.waitForFunction(()=>document.querySelector('#slide-position').textContent?.startsWith('1 / '));
	await page.locator('#editing').click();await ready();assert.equal(await page.locator('#editing').getAttribute('aria-checked'),'true');
	const info=await (await fetch(url+'/test-info')).json();const zip=await JSZip.loadAsync(fs.readFileSync(info.saved));
	assert.equal(JSON.parse(await zip.file('manifest.json').async('string')).mode,'slides');
	const deck=JSON.parse(await zip.file('slides.json').async('string'));assert.equal(deck.title,'技術発表');assert((await zip.file(deck.slides[0].file).async('string')).includes('保存中の追記'));assert.equal(deck.slides.length,12);assert(Object.keys(zip.files).some(n=>n.endsWith('.png')));
	await page.locator('#slides-start').click();await ready();
	await page.frameLocator('#presentation-frame').locator('section.present h1').filter({hasText:'調査結果'}).waitFor();
	assert.equal(await page.frameLocator('#presentation-frame').getByText('画面には見せないメモ').count(),0);
	await page.screenshot({path:path.join(output,'slides-presentation.png')});
	const presenting = page.frameLocator('#presentation-frame');
	const at = (index:number)=>page.waitForFunction(i=>document.querySelector('#presentation').dataset.index===String(i),index);
	await page.waitForFunction(()=>document.fullscreenElement?.id==='presentation');
	assert.equal(await presenting.locator('.controls:visible,.progress:visible,.slide-number:visible').count(),0);
	assert.equal(await page.locator('#presentation button').count(),0);
	const frameBounds = await page.locator('#presentation-frame').boundingBox();
	assert.equal(frameBounds.y,0);assert.equal(frameBounds.height,await page.evaluate(()=>innerHeight));
	const clickPart = async (fraction:number)=>{
		const bounds = await presenting.locator('section.present').boundingBox();
		await page.mouse.click(bounds.x+bounds.width*fraction,bounds.y+bounds.height*.5);
	};
	await clickPart(.5);await at(0);
	await page.keyboard.press('ArrowRight');await at(1);
	await page.keyboard.press('ArrowLeft');await at(0);
	await page.keyboard.press('ArrowDown');await at(1);
	await page.keyboard.press('ArrowUp');await at(0);
	await page.keyboard.press('Enter');await at(1);
	await page.keyboard.press('Shift+Enter');await at(0);
	await clickPart(.85);await at(1);
	await clickPart(.15);await at(0);
	await clickPart(.15);await at(0);
	await page.mouse.wheel(0,100);await at(1);
	await page.mouse.wheel(0,100);await at(2);
	await page.mouse.wheel(0,-100);await at(1);
	await page.mouse.wheel(0,-100);await at(0);
	await page.keyboard.press('End');await at(11);
	await page.keyboard.press('Enter');await at(11);
	await page.keyboard.press('Home');await at(0);
	await page.keyboard.press('o');await presenting.locator('.reveal.overview').waitFor();
	await presenting.locator('section').nth(2).click();await at(2);
	await presenting.locator('.reveal.overview').waitFor({state:'hidden'});
	await presenting.locator('section.present').click({button:'right'});await page.locator('#presentation').waitFor({state:'hidden'});await ready();
	await page.waitForFunction(()=>!document.fullscreenElement);
	assert.equal(await page.locator('#slides-overview').count(),0);
	await page.locator('#slides-present').click();await ready();await page.keyboard.press('Escape');await page.locator('#presentation').waitFor({state:'hidden'});await ready();

	await page.setViewportSize({width:800,height:520});await page.waitForFunction(()=>document.querySelector('#slide-preview').dataset.rendered);await page.waitForTimeout(250);assert.equal(await slide.locator('.reveal-scroll').count(),0);assert.equal(await slide.locator('.slides>section').count(),1);await page.screenshot({path:path.join(output,'slides-compact.png')});
	await save();assert.equal(await rpc('Open',info.saved),true);await page.reload();await ready();await slide.locator('section h1').filter({hasText:'調査結果'}).waitFor();assert.equal(await page.locator('.slide-card').count(),12);
	await page.setViewportSize({width:1800,height:600});
	await page.locator('#slides-start').click();await ready();
	await page.waitForFunction(()=>document.fullscreenElement?.id==='presentation');
	await page.locator('#presentation-frame').evaluate(frame=>frame.contentWindow.focus());
	await page.mouse.click(1790,300);await page.waitForFunction(()=>document.querySelector('#presentation').dataset.index==='1');
	await page.mouse.click(10,300);await page.waitForFunction(()=>document.querySelector('#presentation').dataset.index==='0');
	assert.equal(await page.frameLocator('#presentation-frame').locator('.reveal').evaluate(node=>getComputedStyle(node).backgroundColor),'rgb(240, 240, 240)');
	await page.keyboard.press('Escape');await page.locator('#presentation').waitFor({state:'hidden'});await ready();
	await page.waitForFunction(()=>!document.fullscreenElement);
	await page.setViewportSize({width:1280,height:860});
	await page.locator('.slide-card').first().click();await ready();
	await page.locator('#slides-dual').click();await ready();await page.locator('#presenter').waitFor();
	const audience=await browser.newPage({viewport:{width:1280,height:720}});
	await audience.addInitScript(()=>{
		window.audienceFullscreen=false;window.audienceClosed=false;
		window.go={main:{AudienceWindow:{
			Poll:async withSlides=>{const r=await fetch('/test-audience/state'+(withSlides?'?deck=1':''));if(!r.ok)throw Error('disconnected');return r.json()},
			Control:async(command,index)=>{await fetch('/test-audience/command',{method:'POST',body:JSON.stringify({command,index})})},
			Fullscreen:active=>{window.audienceFullscreen=active},Close:()=>{window.audienceClosed=true}
		}}};
	});
	await audience.goto(url+'/audience.html');
	await audience.locator('#connection').waitFor({state:'hidden'});
	await page.getByText('投影用ウィンドウに接続済み',{exact:true}).waitFor();
	await page.locator('#presenter-notes').getByText('画面には見せないメモ',{exact:true}).waitFor();
	assert.equal(await audience.getByText('画面には見せないメモ').count(),0);
	await page.waitForFunction(()=>document.querySelector('#presenter-current').dataset.rendered&&document.querySelector('#presenter-next').dataset.rendered);await page.screenshot({path:path.join(output,'presenter.png')});
	assert.equal(await page.locator('#presenter-previous').isVisible(),false);
	assert.equal(await page.locator('#presenter-first').isVisible(),true);
	await page.locator('#presenter-fullscreen').click();await audience.waitForFunction(()=>window.audienceFullscreen);
	await page.locator('#presenter-forward').click();await audience.waitForFunction(()=>document.querySelector('#audience-frame').contentDocument.querySelectorAll('section')[1].classList.contains('present'));
	await page.locator('#presenter-previous').waitFor();
	await page.frameLocator('#presenter-previous').locator('h1').filter({hasText:'調査結果'}).waitFor();
	await page.locator('#presenter').focus();await page.keyboard.press('f');await audience.waitForFunction(()=>!window.audienceFullscreen);
	await page.locator('#presenter-pause').click();await page.waitForTimeout(300);const paused=await page.locator('#presenter-timer').textContent();await page.waitForTimeout(1100);assert.equal(await page.locator('#presenter-timer').textContent(),paused);
	await page.locator('#presenter-reset').click();await page.waitForFunction(()=>document.querySelector('#presenter-timer').textContent==='00:00');
	await audience.frameLocator('#audience-frame').locator('section.present').click({button:'right'});await page.locator('#presenter').waitFor({state:'hidden'});await audience.close();
	await page.locator('#slides-dual').click();await ready();await page.locator('#presenter').waitFor();await page.keyboard.press('Escape');await page.locator('#presenter').waitFor({state:'hidden'});
	await page.locator('#settings').click();await page.locator('#nvim-path').fill('/missing/nvim');await page.locator('#mdbook-path').fill('/missing/mdbook');await page.locator('#check-dependencies').click();
	await page.waitForFunction(()=>document.querySelector('#nvim-status').dataset.found==='false'&&document.querySelector('#mdbook-status').dataset.found==='false');
	await page.locator('#settings-dialog').getByRole('button',{name:'キャンセル',exact:true}).click();
	if (process.env.MDZ_NVIM_TEST) {
		await page.locator('#editing').click();await ready();
		await page.locator('#settings').click();await page.locator('[name=editor]').selectOption('neovim');await page.locator('#settings-save').click();await ready();
		await page.waitForFunction(()=>document.querySelector('#engine').textContent==='Neovim');
		await page.locator('#native-input').focus();await page.keyboard.type('ggA NATIVE');await page.keyboard.press('Escape');
		await page.locator('#slides-present').click();await ready();
		await page.frameLocator('#presentation-frame').locator('section.present h1').filter({hasText:'NATIVE'}).waitFor();
		await page.keyboard.press('Escape');await page.locator('#presentation').waitFor({state:'hidden'});await ready();
		assert.equal((await rpc('State')).engine,'neovim');
		await save();
	}
	await page.evaluate(()=>{
		window.testFullscreen={active:false,entered:0,exited:0};
		window.runtime.WindowIsFullscreen=async()=>window.testFullscreen.active;
		window.runtime.WindowFullscreen=()=>{window.testFullscreen.active=true;window.testFullscreen.entered++;};
		window.runtime.WindowUnfullscreen=()=>{window.testFullscreen.active=false;window.testFullscreen.exited++;};
	});
	await page.locator('#slides-start').click();await ready();
	await page.waitForFunction(()=>window.testFullscreen.entered===1);
	await page.keyboard.press('Escape');await page.locator('#presentation').waitFor({state:'hidden'});await ready();
	assert.deepEqual(await page.evaluate(()=>window.testFullscreen),{active:false,entered:1,exited:1});
	await page.evaluate(()=>window.testFullscreen.active=true);
	await page.locator('#slides-start').click();await ready();await page.keyboard.press('Escape');await page.locator('#presentation').waitFor({state:'hidden'});await ready();
	assert.deepEqual(await page.evaluate(()=>window.testFullscreen),{active:true,entered:1,exited:1});
	await page.locator('#new').click();await page.locator('[data-new-kind=document]').click();await ready();assert.equal(await page.locator('#slide-preview').isVisible(),false);await page.frameLocator('#preview').locator('h1').waitFor();
	assert.equal(await page.locator('#editing').getAttribute('aria-checked'),'true');
	await page.locator('#add-page').click();await page.locator('#page-name').fill('拡張子なし');
	await page.locator('#page-dialog button[value=add]').click();await ready();
	await page.waitForFunction(()=>document.querySelector('#current').textContent==='拡張子なし.md');
	assert((await rpc('State')).pages.includes('拡張子なし.md'));

	await page.locator('#add-page').click();await page.locator('#page-name').fill('chapters/比較');
	await page.locator('#page-dialog button[value=add]').click();await ready();
	await page.waitForFunction(()=>document.querySelector('#current').textContent==='chapters/比較.md');
	const beforeOrder=(await rpc('State')).pages;
	const firstPage=page.locator('#pages [data-page="本文.md"]');
	const movedPage=page.locator('#pages [data-page="chapters/比較.md"]');
	await movedPage.dragTo(firstPage,{targetPosition:{x:50,y:3}});
	await page.waitForFunction(()=>document.querySelector('#pages [data-page]').dataset.page==='chapters/比較.md');await ready();
	assert.deepEqual((await rpc('State')).pages,['chapters/比較.md',...beforeOrder.filter(n=>n!=='chapters/比較.md')]);
	assert.equal(await page.locator('#pages [data-page]').first().textContent(),'比較.md');
	await save();assert.equal(await rpc('Open',info.saved),true);await page.reload();await ready();
	await page.waitForFunction(()=>document.querySelector('#pages [data-page]').dataset.page==='chapters/比較.md');
	await page.locator('#files-tab').click();await page.locator('#pages button').filter({hasText:'chapters'}).waitFor();
	await page.locator('#pages-tab').click();await page.waitForFunction(()=>document.querySelector('#pages [data-page]').dataset.page==='chapters/比較.md');

	assert.deepEqual(errors,[]);
	console.log('PASS: slides create/edit/settings/images/import/overflow/order/undo/save/reopen/presentation/overview/ordinary-document regression');
	console.log('Screenshots:',output);
} catch(error) {await page.screenshot({path:path.join(output,'failure.png')});console.error('Screenshots:',output);throw error;}
finally {await browser.close();await fetch(url+'/test-stop');}
